server/db/models/index.js
=> danielle test please reject this

package.json, server/db/db.js, server/db/models/fruit.js, server/db/models/index.js, server/db/models/order.js
=> reviewing models

server/api/fruit.js, server/api/index.js, server/api/users.js
=> merging w Malinda

client/store/fruit.js, server/api/fruit.js, server/db/models/fruit.js, server/db/models/index.js
=> set up fruit reducer

client/components/fruit-single.js, client/components/index.js, client/routes.js, client/store/fruit.js, client/store/index.js
=> creating single fruit component

package-lock.json, script/seed.js, server/api/cart.js, server/api/cart.spec.js, server/api/index.js, server/db/models/index.js
=> seeded models in database and started on cart slice

client/components/button-add-to-cart.js, client/components/fruit-single.js, client/components/index.js, client/routes.js
=> working on addcartbutton

client/components/fruit-all.js, server/api/cart.js
=> fixed api route for cart with passport session user

script/seed.js, server/api/fruit.js, server/api/users.js, server/db/models/fruit.js
=> ADMINTOOLS: Set up admin api routes for fruit. Updated model to Integer

client/components/button-add-to-cart.js, client/components/fruit-all.js, client/components/fruit-single.js, client/routes.js
=> update: single fruit component properly displays now

server/api/cart.js, server/api/fruit.js, server/db/models/order.js, server/db/models/orderFruit.js
=> feat: created instance method calculateItemsTotal

server/api/cart.js, server/db/models/index.js, server/db/models/orderFruit.js
=> update: removed console logs

client/components/button-add-to-cart.js
=> feat: button that adds to cart is complete

client/components/cart.js, client/store/cart.js, server/api/cart.js, server/db/models/order.js, server/db/models/orderFruit.js
=> Feat: created update feature for the cart.

client/components/button-add-to-cart.js, client/store/cart.js, script/seed.js, server/api/cart.js
=> update: add to cart button is up and running!

client/components/button-add-to-cart.js, client/components/cart.js, client/store/cart.js, client/store/cart.spec.js, script/seed.js, server/api/cart.js, server/api/cart.spec.js, server/db/models/order.js
=> fix: removed initialState created for localStorage. Still working on remove item.

client/components/cart.js, client/store/cart.js, server/index.js
=> Local storage4 guests

server/api/cart.js, server/db/models/fruit.js, server/db/models/order.js, util/util-intDeci.js
=> Malindabranch

client/components/admin/SearchBar.js, client/components/admin/adminAllUsers.js, client/components/admin/adminContainer.js, client/components/user-home.js, client/store/user.js, server/api/users.spec.js
=> ADMIN: tests

client/components/cart.js, client/store/cart.js
=> Local storage bug fixes- in progress

client/components/cart.js, server/api/cart.js
=> fixed: bug from merge

client/components/admin/EditSingleUser.js, client/components/admin/SearchBar.js, client/components/admin/adminAllUsers.js, client/components/admin/adminContainer.js, client/components/admin/adminNav.js, client/routes.js, client/store/user.js, script/autofill.js, server/api/users.js
---
Admin Routes Added
Only User Can Access Their Own Page
Admin Can Access Single User Component to Edit Single User
=> Admin components

server/api/cart.js
=> update: fruit model fruit price says in pennies in backend

client/components/cart.js
=> Bug Fix: cart duplicate rendering

server/api/fruit.spec.js
=> test: added test for single fruit

client/components/auth-form.js, client/components/cart.js, client/components/fruit-all.js, client/components/fruit-single.js, client/store/cart.js, public/style.css
=> Feat: CSS for AllFruit, SIngleFruit, Cart

client/components/auth-form.js, client/store/user.js, server/auth/index.js
=> Bug Fix: Error message now displays w wrong user login info

client/components/cart.js, client/components/fruit-all.js, client/components/fruit-single.js, client/store/cart.js
=> Big Fix:Removing duplicate rendering

client/store/cart.js
---
Guest Cart should Operate in Pennies
=> LOCALSTORAGE: ALl Pennies

client/store/cart.js, script/seed.js
=> ENGINEER: Seed Fruit prices reasonable

script/seed.js, server/db/models/fruit.js
=> ENGINEER: Seed has more images
